'use client';

import React, { useState } from 'react';

interface PetCardProps {
  petName: string;
  petNotes: string;
  ownerName: string;
  onUpdate: (updates: { petNotes: string }) => void;
}

export const PetCard: React.FC<PetCardProps> = ({ petName, petNotes, ownerName, onUpdate }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editNotes, setEditNotes] = useState(petNotes);
  const hasPet = petName && petName.trim();

  const handleSave = () => {
    onUpdate({ petNotes: editNotes.trim() });
    setIsEditing(false);
  };

  const handleShare = async () => {
    let message = `🐾 Pet Emergency Card\n\nPet: ${petName}`;
    if (petNotes) message += `\nCare Notes: ${petNotes}`;
    message += `\nOwner: ${ownerName}\n\nGenerated by ImStillHere`;
    if (navigator.share) {
      try { await navigator.share({ text: message }); } catch { /* user cancelled */ }
    } else {
      await navigator.clipboard.writeText(message);
    }
  };

  if (!hasPet) {
    return (
      <div className="mb-8">
        <h3 className="text-lg font-bold mb-1" style={{ color: 'var(--text-primary)' }}>
          🐾 Pet Emergency Card
        </h3>
        <p className="text-sm" style={{ color: 'var(--gray-400)', lineHeight: '1.5' }}>
          No pet information configured. Add a pet name in your profile to create an emergency card.
        </p>
      </div>
    );
  }

  return (
    <div className="mb-8">
      <h3 className="text-lg font-bold mb-1" style={{ color: 'var(--text-primary)' }}>
        🐾 Pet Emergency Card
      </h3>
      <p className="text-sm mb-4" style={{ color: 'var(--gray-400)', lineHeight: '1.5' }}>
        Create a shareable emergency card with {petName}&apos;s info.
      </p>

      <div
        className="rounded-lg p-5 text-center mb-4"
        style={{ backgroundColor: 'var(--card)', border: '1px solid var(--gray-800)' }}
      >
        <p className="text-xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>{petName}</p>
        {petNotes && (
          <p className="text-sm mb-2 text-center" style={{ color: 'var(--gray-400)', lineHeight: '1.5' }}>
            {petNotes}
          </p>
        )}
        <p className="text-xs" style={{ color: 'var(--gray-600)' }}>Owner: {ownerName}</p>
      </div>

      {isEditing ? (
        <div className="mb-4">
          <textarea
            value={editNotes}
            onChange={(e) => setEditNotes(e.target.value)}
            placeholder="Feeding schedule, medications, allergies..."
            rows={3}
            className="w-full px-3 py-2.5 rounded-lg text-base focus:outline-none focus:ring-2 resize-none"
            style={{
              backgroundColor: 'var(--bg-light)',
              border: '1px solid var(--gray-700)',
              color: 'var(--text-primary)',
              minHeight: '80px',
            }}
          />
          <div className="flex justify-end gap-2 mt-2">
            <button
              onClick={() => setIsEditing(false)}
              className="px-3 py-1.5 rounded-lg text-sm font-semibold"
              style={{ color: 'var(--gray-400)' }}
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              className="px-4 py-1.5 rounded-lg text-sm font-bold"
              style={{ backgroundColor: 'var(--accent)', color: 'var(--bg)' }}
            >
              Save
            </button>
          </div>
        </div>
      ) : (
        <button
          onClick={() => { setEditNotes(petNotes); setIsEditing(true); }}
          className="text-sm font-semibold mb-3"
          style={{ color: 'var(--gray-400)' }}
        >
          {petNotes ? 'Edit Care Notes' : 'Add Care Notes'}
        </button>
      )}

      <button
        onClick={handleShare}
        className="w-full font-bold py-3 rounded-lg transition-all btn-press"
        style={{ backgroundColor: 'var(--card)', border: '1px solid var(--gray-800)', color: 'var(--accent)' }}
      >
        📤 Share Pet Card
      </button>
    </div>
  );
};
